# $Id$

CC = gcc

CDEBUGFLAGS = -O

CDEFS = -I/usr/openwin/include  -Dsun -Dsparc -DBSD \
	-D_XFUNCPROTOBEGIN="" -D_XFUNCPROTOEND=""

CFLAGS = $(CDEBUGFLAGS) $(CDEFS)

LIBS = -L/usr/openwin/lib -lXaw -lXmu -lXt -lXext -lX11

SRCS = framedemo.c Frame.c Gcs.c
OBJS = framedemo.o Frame.o Gcs.o

all: framedemo

framedemo: $(OBJS)
	$(CC) -o $@ $(OBJS) $(LIBS)

clean:
	rm -f framedemo
	rm -f *.CKP *.BAK *.bak *.o core errs tags TAGS

Frame.i: Frame.c
	gcc $(CDEFS) -E Frame.c > $@
